### PR TITLE
Create Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by EthanWang706**
This file will be probably translate by @Iso-Polaris

### CODE REVIEW

**Comment by ChrisAdderley** [comment]
Sorry I missed this! Too may mods to maintain!

**Comment by EthanWang706** [comment]
@ChrisAdderley What do you mean by too may mods?

**Comment by ChrisAdderley** [comment]
Oh, I maintain like... 11 KSP mods? It's easy to miss things when I have a lot to work on.

**Comment by EthanWang706** [comment]
@ChrisAdderley Ok, I will tell you by forum if I leave a commit.

**Pull request merged**
